In [72]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv('/content/drive/MyDrive/Google Colab/car.csv')

In [75]:
df

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [76]:
x_sample = df.iloc[ : , :-1]
y_sample = df.iloc[:,-1]
x_list=x_sample.to_dict('split')
x_list=x_list['data']
y_list = y_sample.to_list()

In [ ]:
x_list

In [78]:
length = len(x_list)
length

1727

In [ ]:
random_array = list(np.random.choice(length, length))
random_array

In [41]:
length80 = int(length * 0.8)
# length80
random80 = random_array[:length80]
random20 = random_array[length80:]

In [80]:
x_test = {}
y_test = {}
x_train = {}
y_train = {}

for i in random80:
    x_train[i] = x_list[random_array[i]]
    y_train[i] = y_list[random_array[i]]

for i in random20:
    x_test[i] = x_list[random_array[i]]
    y_test[i] = y_list[random_array[i]]

In [132]:
x_test

{9: ['high', 'vhigh', '5more', '4', 'small', 'med'],
 16: ['low', 'vhigh', '2', 'more', 'med', 'low'],
 28: ['med', 'med', '5more', '2', 'big', 'low'],
 33: ['low', 'high', '4', '2', 'med', 'high'],
 55: ['low', 'vhigh', '4', '2', 'med', 'med'],
 56: ['low', 'vhigh', '4', '4', 'small', 'med'],
 60: ['high', 'high', '4', '4', 'big', 'high'],
 65: ['med', 'vhigh', '3', '2', 'big', 'low'],
 70: ['vhigh', 'low', '5more', '4', 'big', 'high'],
 73: ['vhigh', 'vhigh', '3', 'more', 'big', 'high'],
 74: ['vhigh', 'vhigh', '2', '4', 'big', 'high'],
 103: ['high', 'high', '3', '2', 'med', 'high'],
 108: ['med', 'vhigh', '2', '4', 'small', 'high'],
 112: ['med', 'low', '3', 'more', 'small', 'low'],
 118: ['low', 'high', '3', '4', 'small', 'med'],
 120: ['med', 'high', '2', 'more', 'med', 'med'],
 127: ['high', 'low', '4', '2', 'small', 'low'],
 136: ['high', 'high', '3', '4', 'med', 'med'],
 137: ['low', 'med', '2', '2', 'big', 'low'],
 152: ['med', 'vhigh', '5more', 'more', 'med', 'high'],
 155: 

In [ ]:
len(y_test)

In [ ]:
x_train

In [99]:
unique_y_train = set(y_train.values())
y_train_list = list(y_train.values())
class_probability = {}
count_class = {}
for i in unique_y_train:
    count_class[i] = y_train_list.count(i)
    class_probability[i] = round(count_class[i]/len(y_train), 3)

In [ ]:
count_class

In [131]:
unique_y_train

{'acc', 'good', 'unacc', 'vgood'}

In [ ]:
class_probability

In [134]:
x_test[1204]

['vhigh', 'vhigh', '4', 'more', 'med', 'low']

In [135]:
y_test[1204]

'unacc'

In [121]:
def class_determine(feature,column,type_class):
    count=0
    for i in x_train:
      if feature == x_train[i][column] and y_train[i] == type_class:
        count += 1
    return count/count_class[type_class]

In [ ]:
feature_probability = {}
product = 1
product2 = 0
for i in x_test:
  product2 = 0
  for k in unique_y_train:
      c = 0
      product = 1
      print(i, k)
      for j in x_test[i]:
        # print(j)
        product *= class_determine(j, c, k)
        c += 1 
        #print(product)
      product *= class_probability[k]
      print(product)
      if product2 < product:
        product2 = product
        feature_probability[i] = k
  print('---')

In [ ]:
feature_probability

In [ ]:
y_test

In [148]:
unique_value = {}
count = 0
for i in unique_y_train:
    unique_value[i] = count
    count += 1

In [ ]:
unique_value

In [158]:
y_predict = []
for i in feature_probability:
    y_predict += [unique_value[feature_probability[i]]]
    #print(unique_value[feature_probability[i]])
y_predict = np.array(y_predict)

In [159]:
y_predict

array([1, 3, 1, 1, 1, 1, 1, 3, 3, 3, 1, 3, 1, 1, 1, 1, 3, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 3,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 0, 1, 3, 1, 1,
       3, 1, 2, 2, 1, 1, 1, 1, 2, 3, 1, 3, 3, 1, 1, 3, 1, 3, 1, 1, 1, 1,
       0, 1, 3, 3, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 1,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
       3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 3, 3, 1,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 3, 3, 1, 1, 1, 1, 1, 1, 3,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 2, 3, 1, 3, 1, 3, 1,
       1, 1, 1, 3, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1,
       1, 2, 0, 1, 3, 3, 1, 2, 1, 1, 3, 1, 1, 1, 1, 3, 3, 3, 3, 3, 1, 3,
       1, 3, 1, 3, 1, 1, 1, 2, 3, 1, 1, 1, 3, 0, 1, 2, 1, 2, 1, 1, 1, 3,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2,
       1, 3, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,

In [161]:
y_test_array = []
for i in y_test:
    y_test_array += [unique_value[y_test[i]]]
    #print(unique_value[feature_probability[i]])
y_test_array = np.array(y_test_array)

In [ ]:
y_test_array

In [165]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print('Confusion_matrix=>')
print(confusion_matrix(y_test_array, y_predict))
print('Classification Report=>')
print(classification_report(y_test_array, y_predict))

Confusion_matrix=>
[[ 11   0   2   5]
 [  0 203   0  11]
 [  0   0  10  10]
 [  0  15   4  47]]
Classification Report=>
              precision    recall  f1-score   support

           0       1.00      0.61      0.76        18
           1       0.93      0.95      0.94       214
           2       0.62      0.50      0.56        20
           3       0.64      0.71      0.68        66

    accuracy                           0.85       318
   macro avg       0.80      0.69      0.73       318
weighted avg       0.86      0.85      0.85       318

